### ISSUE TITLE
`purs ide` mode and new files

### ISSUE THREAD

**Issue by coot** [ethul/purs-loader#100]
Every time I add a new file, I need to restart webpack so that it's loaded.   If we can get that information from webpack, we could ask purs ide to compile that file [using](https://github.com/purescript/purescript/blob/master/psc-ide/PROTOCOL.md#rebuild)

**Comment by ethul** [comment]
Thanks for bringing this up. Apologies for the delay.

Which version for the purs-loader are you using? Also, are you able to provide your webpack config?

I am on webpack 1.x, and with the 3.0.0 purs-loader I haven't had to restart webpack to pick up new files. They are picked up when they are imported from existing files. Perhaps there is something going on in the config?

**Comment by coot** [comment]
Sorry for the delay too.  

I am using `webpack` 2.x with `purs-loader` 3.0.0. I don't have a public repo for that, but I'll do something about it.

**Comment by ethul** [comment]
I came across this issue using webpack 3. I need to investigate further, but it seems to be an issue on webpack 2/3 and not webpack 1. In ide mode, it looks like we will need to attempt to add any files to the internal purs module mapping that are dependencies of files that are reloaded.

We might be able to do something here to resolve this:
https://github.com/ethul/purs-loader/blob/aaf98ca8bccce1a8e2330184fb19aa4399f10f25/src/to-javascript.js#L115-L119

**Comment by coot** [comment]
Thanks @ethul I will test it tomorrow.

**Comment by ethul** [comment]
Great! Thanks
