### ISSUE TITLE
Correct inline compile configuration for vue-cli webpack template

### ISSUE THREAD

**Issue by niquelbarron** [ethul/purs-loader#107]
Hi, 

Hope I am stating this correctly and thank you in advance for the library. It is very useful even with the current configuration.

My issue is that it only completes with a usable imported file if I set the bundle option to true. 
purs-loader compiles my file if I set the flag to false but in debug the required files are not accessible or not included in the compiled js. 

Currently I can only fully compile and bundle all dependencies in one file combining all code in an import into one js file. I would like to be able to import/compile inline a separate purescript file and function into components from multiple purescript files and not generate one bundle file.

With bundle set to true if I add an additional purescript file in a separate component it overwrites the bundle and fails. I can combine all functions into one purescript file but that workflow isn't ideal.

That being said is there a known vue-cli configuration that allows for inline compilation instead of one single bundle file?

My configuration is below.

"vue": "^2.5.2",
"webpack": "^3.6.0",
vue-cli: 2.9.2
purescript-compiler 0.11.7

   ```
      {
        test: /\.purs$/,
        loader: 'purs-loader',
        exclude: /node_modules/,
        options: {
          src: [
            'src/vuex/utils/pure/bower_components/purescript-*/src/**/*.purs',
            'src/vuex/utils/pure/src/**/*.purs'
          ],
          bundle: true,
          psc: 'psa',
          watch: true,
          warnings: true,
          output: 'src/vuex/utils/pure/output/'
        }
      },
 ```

**Comment by ethul** [comment]
Thanks for the write-up. Apologies for the delay in response. I appreciate your patience.

I was looking into vue-cli briefly and I was curious if you had a bare-bones example that can replicate the issue. I think your loader configuration looks okay, as far as I can tell. Out of curiosity, which files require the purescript files?

**Comment by niquelbarron** [comment]
I do not have a simple example, I can build a simple one next week. I am requiring the purescript files in my VUEX mutations and actions. It only errors when I set bundle to false and attempt to import multiple purescript modules. My workaround is to re-export all functions and modules into one module file and set bundle to true. Another workaround is to use a separate watcher tool chokidar and compile each file separately then copy them over. Just was looking for an all inclusive solution.

**Comment by niquelbarron** [comment]
This can be closed I discovered the issue. 
The short answer is user error. The fix was to add the output directory to the root .eslintignore file.
Javascript errors such as forgetting a semicolon or not exporting modules correctly in javascript modules in the output directory were crashing the compile in the webpack build.

**Comment by ethul** [comment]
Thanks for the update. Glad it works!
