### ISSUE TITLE
Generate .psci file

### ISSUE THREAD

**Issue by ethul** [ethul/purs-loader#11]
It would be handy if a .psci file is generated.

**Comment by stkb** [comment]
:thumbsup: Yes please :)

I also want to thank you for creating purs-loader. I had a read through old issues and saw that you were at one point thinking of deprecating it, but as someone who prefers to use only webpack as their build tool, it's much appreciated that this exists.

**Comment by ethul** [comment]
Hope to add psci generation soon! And thanks for checking out the purs-loader. It's true I wasn't sure that it would fly originally, but I also prefer going the webpack-only route. Cheers!

**Comment by ethul** [comment]
Note: add an option to disable psci generation, but enable it by default.
