### ISSUE TITLE
Not rebuilding in Worker

### ISSUE THREAD

**Issue by dakom** [ethul/purs-loader#114]
Not sure if the Worker aspect is really the culprit, but I'm just diving into Purescript stuff and wanted to setup a project where the logic is in a Web Worker.

Here's the boilerplate so far: https://github.com/dakom/hello-purescript-worker

It seems to be working, except that when I change the purescript code (in src/app/pure/Main.purs) - the page refreshes but there's no actual difference. As though it's just loading from cache.

You can see I've been testing by changing the string [here](https://github.com/dakom/hello-purescript-worker/blob/master/src/app/pure/Main.purs#L47) to incremental numbers but it's always the same result (after initial load... if I kill webpack and then restart it, the changes are visible)

**Comment by dakom** [comment]
Oh interesting... once I started using the psc-ide-vim plugin, this resolved.

I guess an ide instance needs to be kickstarted from the outside or something?

**Comment by ethul** [comment]
Are you able to provide the config for the purs-loader? The loader should spin-up a psc-ide-server instance without needing to start one externally. The config for the purs-loader should be something like the following.

https://github.com/ethul/purescript-webpack-example/blob/ecebb9d8808477b33d50388a615f04be331646e7/webpack.config.js#L40-L57

**Comment by dakom** [comment]
Sorry - I ended up just watching the `output` folder instead of purs-loader... my apologies! I'll close this issue for now. Thanks!
