### ISSUE TITLE
Source maps are only generated when not using PSC IDE fast rebuilds

### ISSUE THREAD

**Issue by sriharshachilakapati** [ethul/purs-loader#116]
When I enable fast rebuilds by adding `pscIde: true` to the options, the sourcemaps are not being updated.

![image](https://user-images.githubusercontent.com/4593204/50477701-75d35d80-09f3-11e9-9f49-6c9d3b412a63.png)

How to fix this issue while still retaining the fast rebuild feature? I can't disable fast rebuild, as I have 1500 modules, and compiling is taking me 6 seconds to complete and dev-server auto reload to trigger.

**Comment by kRITZCREEK** [comment]
The ability to do this was added to `purs ide` in 0.12.1: https://github.com/purescript/purescript/pull/3449

Check out the `codegen` parameter in here: https://github.com/purescript/purescript/blob/9446c8bb5f6cd5e74b3f1eb787cfded684391400/psc-ide/PROTOCOL.md#rebuild

You'll need to thread through the configuration parameter through purs-loader and then things should work with `codegen: ["js", "sourcemaps"]`.

**Comment by sriharshachilakapati** [comment]
Glad to know that it is already solved, but unfortunately I'm still on 0.11.7 due to some internal libraries not being updated till now. Will try to update them first. Please tell if there is a solution for 0.11.7 users too.

**Comment by kRITZCREEK** [comment]
Unfortunately not. In 0.11.7 land the `purs ide` rebuilds can't produce sourcemaps.

**Comment by sriharshachilakapati** [comment]
Good, now I have one more compelling reason to ask internally to update the libraries. Thanks for the response.

**Comment by ethul** [comment]
Thanks for the thread and replies. This might be good information to add to
the readme of the loader. Thanks!

**Comment by kRITZCREEK** [comment]
I don't think this is purely a documentation issue, the extra parameter will need to be added to every "rebuild" request sent to `purs ide`, so a tiny bit of configuration will need to be added to purs-loader and threaded through.

**Comment by ethul** [comment]
Welcome!
