### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by sriharshachilakapati** [ethul/purs-loader#123]
I just started to port the project containing 4936 modules currently to 0.12 from 0.11 and started seeing this error.

~~~log
glob error { Error: EMFILE: too many open files, scandir '/Users/sriharshachilakapati/Projects/********/Frontend/purescript/src/Application/Helpers'
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/Users/sriharshachilakapati/Projects/********/Frontend/purescript/src/Application/Helpers' }
~~~

Any idea what is happening?

**Comment by sriharshachilakapati** [comment]
I just removed the bower_components, updated the bower.json by hand picking the correct versions, did `bower i` and then fired up webpack with purs-loader.

However there are a ton of source code errors, not just imports but also other issues. After manually fixing all the errors using `pulp -w build`, it started working.

But then, it should be showing the errors just like pulp would right?

**Comment by ethul** [comment]
Just to make sure that I understand. You mention that you fixed all of the errors. Does the project compile correctly now using the loader? Are you able to provide your webpack config?

**Comment by sriharshachilakapati** [comment]
Yes of course, it compiled using the loader fine once I fixed all the errors. The problem is present when there are a lot of errors.
