### ISSUE TITLE
How to import image generated by image-webpack-loader

### ISSUE THREAD

**Issue by srghma** [ethul/purs-loader#130]
When using js with
 https://www.npmjs.com/package/image-webpack-loader one can write

```js
import image from "./image.png"

console.log(image) # will output base64 encoded string OR relative path to image from dist directory
```

But how to import image from purescript code? FFI?

**Comment by ethul** [comment]
Currently, this functionality is not supported. The FFI does not pass
through webpack loaders.

**Comment by srghma** [comment]
@ethul I have no idea how to make it possible, do you have one?

**Comment by ethul** [comment]
I've looked into this previously and did not come up with a good way to do this. I am open to ideas on how to make this possible.

**Comment by srghma** [comment]
actually image import is working without changes

https://github.com/ethul/purescript-webpack-example/pull/10

**Comment by ethul** [comment]
Great! Thanks for testing this out.
