### ISSUE TITLE
Prefer purescript npm bins when installed

### ISSUE THREAD

**Issue by ethul** [ethul/purs-loader#21]
Like purescript-contrib/gulp-purescript#19

**Comment by natefaubion** [comment]
FYI, if you launch webpack within an npm script, everything in `./node_modules/.bin` will be in your path, and it should use the npm-installed binaries.

**Comment by ethul** [comment]
Ah. Nice. Thanks for the tip.

**Comment by ethul** [comment]
Maybe a documentation update would be helpful for this.

**Comment by ethul** [comment]
Closing since the loader no longer uses any purescript binaries. This is done by the [purescript-webpack-plugin](https://github.com/ethul/purescript-webpack-plugin).
