### ISSUE TITLE
Hello World not compiling

### ISSUE THREAD

**Issue by haf** [ethul/purs-loader#23]
See commit https://github.com/haf/purescript-recq/commit/c1ead770753a82b86969a449e0d7ef3003849ec9 for example

Trying to import Debug.Trace:

https://github.com/purescript/purescript/wiki/Language-Guide:-Intro

**Comment by ethul** [comment]
Please see #22 

`Debug.Trace` is no longer in purescript 0.7.

**Comment by ethul** [comment]
Closing in favor of #22
