### ISSUE TITLE
Consider using purescript-node-child-process?

### ISSUE THREAD

**Issue by hdgarrood** [ethul/purs-loader#35]
I've just published v0.3.2 of [purescript-node-child-process](http://pursuit.purescript.org/packages/purescript-node-child-process/0.3.2). It's used by pulp, which has a fairly comprehensive test suite, so hopefully that will put your mind at ease.

If you want, you could swap out your bindings for this library. I should be clear about why I think this would be a good thing:

* It would serve as a better example for people who read the source of purs-loader
* It would help us improve the `node-child-process` API
* It might uncover bugs in `node-child-process` (although I am fairly sure that the part purs-loader would use doesn't have any bugs)
* It might be easier for you if you ever need any more of the Node `child_process` API

Admittedly, these are more in the interest of the community at large rather than purs-loader in particular. So please feel free to ignore this! Alternatively, if you agree, I would be happy to do the work and send a PR.

**Comment by ethul** [comment]
Thanks for the heads up on `purescript-node-child-process`. Your library looks great!

I'd definitely be interested to migrate to using it. However, pending #34, this loader may be replaced with a plugin. So perhaps it would be best to hold off on a PR until #34 is figured out. But note that if the plugin pans out, I will be migrating it to purescript and will certainly use the `purescript-node-child-process` library.

If you're still interested in submitting PRs for migrating to the `purescript-node-child-process` library, the [gulp-purescript](https://github.com/purescript-contrib/gulp-purescript) package might be a good candidate. I've raised purescript-contrib/gulp-purescript#58 as a reminder so I remember to do this at some point. But I would definitely be open to a PR for it.

**Comment by hdgarrood** [comment]
Ok, sounds great :) I will probably send a PR to gulp-purescript at some point in the not too distant future, then.

**Comment by ethul** [comment]
Great. Thanks!

**Comment by ethul** [comment]
Closing since #34 has been merged. The heavy lifting is now done by the [purescript-webpack-plugin](https://github.com/ethul/purescript-webpack-plugin). This will be migrated to purescript and will definitely leverage the `purescript-node-child-process` module.
