### ISSUE TITLE
purs-loader generates invalid requires on windows

### ISSUE THREAD

**Issue by asvyazin** [ethul/purs-loader#41]
In particular it produces something like `module.exports = require('.\output\moduleName\fileName.js')` and then webpack generates some cryptic error 'cannot find file "....utputoduleNameileName.js"' (note skipped letters).

Loader should instead generate `'./output/moduleName/fileName.js'` or `'.\\output\\moduleName\\fileName.js'`. Locally I *"fixed"* the bug with ugly hack - added `.replace(/\\/g, '\\\\')` to generated path. And actually I'm not sure how it really should be fixed.

**Comment by ethul** [comment]
I am wondering if you can provide a little more information here. I don't have an easy way to try this on windows, but where are these require statements? Can you show the whole file?

The plugin and loader don't hardcode any path separators, except for `--require-path=../` in the plugin. Could this be the issue? Otherwise just the output from `psc` and `psc-bundle` are being used.

If you can provide a bit more detail it would be most helpful here.

**Comment by asvyazin** [comment]
Line 118 in index.js, purs-loader-0.6.0-beta.3 (compiled version from npm, only js here)
Or line 80 in Loader.purs, original purescript sources.

Plugin of course doesn't hardcode separators, it uses node module "path" for generating relative filepath and then inserts this filepath in js code as is. Unfortunately on windows system path separator is '\' - special symbol in almost every programming language so it does not work

**Comment by ethul** [comment]
[Line 80](https://github.com/ethul/purs-loader/blob/17f22f868b851e50081844562627a7a8a414dcaa/src/PursLoader/Loader.purs#L80) of the `Loader.purs` uses the `resourcePath` (from webpack) and the `bundleOutput` path (which is provided in the user's webpack config or defaulted to a value generated using node's `path.join`). So I am unsure why the paths are invalid here.

Would you be willing to do a little inline modification to the index.js of the purs-loader and console.log the value of `resourceDir` on line 95? And also the value of `path` on line 94?

When I do that I get:

```
resourceDir: /Users/path/purescript-loader-reload-issue-repro/src
path: ../output/bundle.js
```

In the code I added:
```javascript
console.log('resourceDir: ' + resourceDir);
// ...
console.log('path: ' + path.value0);
```

**Comment by asvyazin** [comment]
Paths are valid. But it's invalid to use unescaped paths (though perfectly valid) in code. Weird, I know. Well, that's windows.

With your modifications I get:
```
resourceDir: D:\Development\Web\MyBooks.purs\src\Entries\Index
path: ..\..\..\output\bundle.js
```
No problem here, all valid. But then:
```
ERROR in ./src/Entries/Index.purs
Module not found: Error: Cannot resolve module '....outpuundle.js' in D:\Development\Web\MyBooks.purs\src\Entries
 @ ./src/Entries/Index.purs 1:17-50
```

**Comment by ethul** [comment]
Thank you for the output. You're right. Looks like we need some escaping here. I will work on a fix.

**Comment by ethul** [comment]
Sorry this took so long, but would you be able to give this fix a try?

Please use `purs-loader@0.6.0-beta.6` and `purescript-webpack-plugin@0.2.0-beta.7`

**Comment by asvyazin** [comment]
Yes, it works very well.

And I see that you also had replaced child_process with cross-spawn-async. That's good, it was a problem too. Now purs-loader really works out of the box (on windows), thank you :)

**Comment by ethul** [comment]
Great! Thanks for testing. Glad it works.
