### ISSUE TITLE
Help Request: Include an Example app that uses purs-loader

### ISSUE THREAD

**Issue by antonycourtney** [ethul/purs-loader#5]
Would it be possible to add an "Example" folder with a working "Hello Purescript" example app with a working webpack.config.js?

Apologies for the newbie ask, just getting started with PureScript (but familiar and happy with webpack for JS projects).

I tried starting with the webpack config from the README.  It produces a valid JS bundle, but it's not obvious to me how to use that generated file.  If I do:

    var r = require ('./dist/World.js');

from node I get an empty object in r, even if the original World.purs had an export list.

This is likely just misunderstanding on my part on how to use the resulting output.

**Comment by ethul** [comment]
Good idea!

I've added an example in commit ebf06d39692b92058df757b2ec0009f0935d4563

Also, on a side note (as mentioned in #4), I am unsure if there is a good use-case for the `purs-loader`. At first, I thought it might be handy; however, upon digging into it more and testing it out, I am not so sure anymore. The problem I see is that each PureScript file will be compiled at each `require` point by webpack. I suppose this might work, but I think have a compile step for the PureScript code before webpack runs might ultimately be the best way to go.

I am still tossing around ideas here and admit that I haven't had too much of a chance to go forward with this, but I am open to other ideas or suggestions on a direction for this loader.
