### ISSUE TITLE
What versions of Purescript does purs-loader@1.0.0 support?

### ISSUE THREAD

**Issue by wegry** [ethul/purs-loader#62]
Since Purescript 0.9.1 doesn't explicitly specify FFI files, can purs-loader@1.0.0 support older versions (like 0.8)?.

**Comment by ethul** [comment]
Yes, 1.0.0 is for purescript 0.8. The NPM dist-tags are used to match up
the loader version with the corresponding purescript version.

**Comment by wegry** [comment]
Looks like my team will have to find a way to just hack around purescript/purescript/issues/2097.

**Comment by ethul** [comment]
Is there something on the purs-loader side that can help here? Maybe remove
purescript from the peer dependencies? Just want to make sure I understand
the issue.

**Comment by wegry** [comment]
Yeah, it might be an issue. My team currently uses `node 6` and has a separate install of psc in our build process. I was hoping to get away with only installing `psa` and then hooking onto our current install of `psc 0.8` until we upgrade to a version of `psc` that's compatible with `node 6`.

**Comment by ethul** [comment]
I am open to removing peer dependencies in the 1.x series. It has already
been removed in the 2.x series.

**Comment by wegry** [comment]
Does the 2.x series support psc@0.8?

**Comment by ethul** [comment]
Only psc 0.9

**Comment by wegry** [comment]
Bah, then yes, that would be great if you could remove the peer dependency on purescript@0.8.

**Comment by ethul** [comment]
I will do that. It might be in the next day or so. I will keep you posted.

**Comment by ethul** [comment]
Okay, peer dependencies have been removed in version 1.1.0

**Comment by wegry** [comment]
Thanks!

**Comment by ethul** [comment]
Welcome
