### ISSUE TITLE
Does purs-loader work with JS loaders like eslint-loader?

### ISSUE THREAD

**Issue by wegry** [ethul/purs-loader#63]

**Comment by ethul** [comment]
The JS FFI files are passed through webpack like other JS files. I believe
the eslint loader should work. However note that the purescript compiler
reads the FFI files as-is.

**Comment by wegry** [comment]
Thanks for the quick response!

**Comment by ethul** [comment]
Welcome!

**Comment by paulyoung** [comment]
Is it possible to make the PureScript compiler see the files after they have been transpiled?

For example, when creating an FFI module for an ES6 class that includes JSX.

Thanks!

**Comment by ethul** [comment]
I recall looking into this before. I didn't see a way to do this. However,
I am open to discuss ideas on how this could work.

**Comment by paulyoung** [comment]
I'm currently just creating JS files that re-export things, like this:

```
exports.ui = require('MyReactComponent.js').default;
```
