### ISSUE TITLE
Getting JSON errors for ide-purescript

### ISSUE THREAD

**Issue by dkoontz** [ethul/purs-loader#65]
I'm trying to use the same config for both my regular build and for ide-purescript. I can't figure out a way to get the loader to output just the output JSON from psc. Is there a flag that could enable this that I could conditionally enable?

**Comment by ethul** [comment]
In the [options](https://github.com/ethul/purs-loader#options) you can pass `pscArgs`; e.g., `pscArgs: { jsonErrors: true }`. Does this allow you to get the JSON output for you use-case?

**Comment by dkoontz** [comment]
I tried that but Webpack still gives back other output. After digging in some more I realize this is not really a purescript-loader issue but a more general webpack issue.

**Comment by ethul** [comment]
Thanks for digging into this and for the update.
