### ISSUE TITLE
When a new file fails to compile it is not watched

### ISSUE THREAD

**Issue by ethul** [ethul/purs-loader#74]

**Comment by forestbelton** [comment]
Hey @ethul, are you actively working on this? If not, I'd like to give it a shot. This is a pretty big pain point for me while developing PureScript applications that have a heavy JavaScript integration.

**Comment by ethul** [comment]
I would definitely appreciate a PR for this if you have a chance to work on
it. Thanks!

**Comment by ethul** [comment]
@forestbelton I was just thinking that it might work to omit passing an error to the webpack callback upon failure. This may keep the file in the watch. So we would make the following a no-op:

https://github.com/ethul/purs-loader/blob/5f4d6751efdb215207e7ee87b424b14c4dc041d1/src/index.js#L88

I haven't tried this, but this is how the load works when psc-ide is used. Might  be worth a try.

**Comment by ethul** [comment]
Or not a no-op, but just pass back the previous JS to the callback.

**Comment by tbenst** [comment]
Here's a possible solution: https://github.com/shama/webpack-stream/pull/126/files

**Comment by ethul** [comment]
Thanks for the tip. I was testing out something like this over the weekend. Might very well be the way to go.

**Comment by tbenst** [comment]
I did an attempt here: https://github.com/tbenst/purs-loader/commit/b8aaa2f95916daf0d3b492c3c593ead1f120c4d8

But I haven't been able to test as I can't seem to get purs-loader installed via github. I imagine I'm missing a compilation step in building the package.

**Comment by ethul** [comment]
Thanks! I think something along these lines might work. I will take a look this weekend and try out some ideas.

**Comment by ethul** [comment]
I've published a beta release that should fix  this issue. If anyone is willing to give it a try, that would be great! You can install the release under the `beta` dist tag.

```
npm install purs-loader@beta
```

In this release, there is a new option called `watch`. Please set this to true in your webpack config if you are running webpack in watch mode.

Thanks!

**Comment by dikmax** [comment]
In https://github.com/ethul/purs-loader/blob/topic/error-handling/src/to-javascript.js
there's a typo which prevents anything to be built. 

`psMoudle` -> `psModule`.

**Comment by ethul** [comment]
Thank you for catching this. I've fixed this in `2.4.0-beta.1`.

**Comment by dikmax** [comment]
Works without any issues now. Awesome!

Thank you!!!

**Comment by ethul** [comment]
Great! Thank you for confirming

**Comment by dikmax** [comment]
Just noticed, builds stop working if a file is removed.

**Comment by ethul** [comment]
If imports to the file removed are also removed, does the build work once again?

**Comment by dikmax** [comment]
Unfortunately, I cannot reliably reproduce this issue, but it has something to do with dependencies. When I find suitable scenario I'll write it.

**Comment by tbenst** [comment]
I'm also having occasional difficulty, it works initially but occasionally stops watching after many minutes. I know that's vague and will report back if I notice a pattern

**Comment by ethul** [comment]
Thanks for following up on this. I will try out the ErrorParsingModule and UndefinedTypeVariable cases.

Thanks!

**Comment by ethul** [comment]
I released `2.4.0-beta.2` which adds a check when a module is not in the module mapping. The goal is to handle when files are removed.

I haven't been able to reproduce the watch issue yet. I tried the two errors above, but it seems to be working for me. Maybe we can track this as a new issue if we can get a reproducible case.

**Comment by ethul** [comment]
https://github.com/ethul/purs-loader/releases/tag/2.4.0
