### ISSUE TITLE
PureScript 0.11

### ISSUE THREAD

**Issue by ethul** [ethul/purs-loader#89]
Release checklist: purescript/purescript#2745

### Impacting

purescript/purescript#2336

**Comment by ethul** [comment]
Waiting on the decision from purescript-contrib/node-purescript-bin#45. There may be no changes necessary to support 0.11.

**Comment by cencarnacion** [comment]
Any update on this issue?

**Comment by ethul** [comment]
Yes! Working on a branch.

**Comment by cencarnacion** [comment]
Good to here that! Thanks!

**Comment by ethul** [comment]
Welcome!

**Comment by cencarnacion** [comment]
Do you have snapshots available?

**Comment by ethul** [comment]
I don't have one yet. I should be able to make headway on this this weekend.

However, depending on your setup, the current purs-loader version may work
for PureScript 0.11.

If you have PureScript installed globally, and the wrapper scripts "psc",
etc., work for you, then the purs-loader should be working without any
modification.

When PureScript is installed locally via NPM, it does work since the
wrapper scripts are not included in the node_modules/.bin.

**Comment by cencarnacion** [comment]
Yes, you're right!

**Comment by pbrant** [comment]
@ethul Just wanted to mention I tried out the beta version and it works great. Thanks very much for your efforts here!

**Comment by ethul** [comment]
Great! Glad it is working well for you. Thanks for giving it a go!
