### ISSUE TITLE
loaderUtils.parseQuery() received a non-string value which can be problematic

### ISSUE THREAD

**Issue by louisch** [ethul/purs-loader#92]
`loaderUtils.parseQuery()` will be deprecated in favor of `getOptions()` in the next major version of `loader-utils`. The call should probably be replaced.

See: <https://github.com/webpack/loader-utils/issues/56>

**Comment by ethul** [comment]
Thanks for the heads up. We have a pull request open for this:
https://github.com/ethul/purs-loader/pull/86

I will merge it in once I test things out in weback2.

**Comment by ethul** [comment]
Closed by #86
